spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

brevo:
  api:
    key: ${BREVO_API}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

razorpay:
  key: ${RAZORPAY_KEY}
  secret: ${RAZORPAY_SECRET}

logging:
  level:
    root: INFO
    com.payae: DEBUG