spring:
  datasource:
    url: jdbc:postgresql://ep-icy-math-a10ww8ba-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_Mf1scEP0ntUD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

brevo:
  api:
    key: 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

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

razorpay:
  key: ${RAZORPAY_KEY}
  secret: ${RAZORPAY_SECRET}

logging:
  level:
    root: INFO
    com.payae: DEBUG